name: e_wallet
description: "Solusi Keuangan."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  # QR CODE
  qr_flutter: ^4.1.0 # masih pakai versi lawas
  mobile_scanner: ^3.5.0 # masih pakai versi lawas
  vibration: ^3.1.4
  image_picker: ^1.0.4
  google_mlkit_barcode_scanning: ^0.11.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Auth & Cache
  google_sign_in: ^6.3.0 # older than 7.2.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  shared_preferences: ^2.2.2
  http: ^1.2.0

  # formatter
  timeago: ^3.6.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon_app.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_app_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/google-logo.png
    - assets/images/icon_app.png
    - assets/images/icon_app_foreground.png